name: bbb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^0.13.6
  swipe: ^0.0.1
  flutter_swipe: ^1.0.1
  graphql_flutter: ^5.1.2
  flutter_swiper: ^1.1.6
  xen_popup_card: ^0.0.1
  badges: ^2.0.3
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/icon/
  fonts:
    - family: Quicksand
      fonts:
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf
      - asset: assets/fonts/Quicksand-SemiBold.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf